

# Notice : aspect = wid/hei, wid is the horizon side length of img, hei is vertical side length of img 

SMALL_LIGHTBAR_SINGLE_AREA_RANGE = [1,5*1000]
SMALL_LIGHTBAR_SINGLE_ASPECT_RATIO_RANGE = [0.01,1]
SMALL_LIGHTBAR_CENTER_DISTANCE_RANGE = [1,1000]
SMALL_LIGHTBAR_TWO_AREA_RATIO_RANGE = [0.23,5.61]
SMALL_LIGHTBAR_TWO_ASPECT_RATIO_RANGE = [0.28,3.09]



BIG_REC_AREA_RANGE = [10,350*1000]

BIG_REC_ASPECT_RATIO_RANGE = [1,5]





GAUSSIAN_BLUR_KERNAL_SIZE = [3,3]
GAUSSIAN_BLUR_X = 1
CLOSE_KERNEL_SIZE = [2,2]
STRECH_MAX = None


RED_ARMOR_YUV_RANGE = [152,255]
RED_ARMOR_BINARY_ROI_THRESHOLD = 127


BLUE_ARMOR_YUV_RANGE = [145,255]
BLUE_ARMOR_BINARY_ROI_THRESHOLD = 90




