# Debug modifiable value:
# gun_pivot_height_above_ground 
# max_shooting_hei_above_ground 
# target_min_hei_above_ground 
# max_shooting_dis_in_pivot_frame 
# target_min_hei_above_ground 
# pitch_range


R_K4_dt_near: 0.001
R_K4_dt_far: 0.005
R_K4_error_tolerance: 0.03
bullet_mass: 0.0032
bullet_speed: 27
camera_x_len: 0.12
camera_y_len: 0.075
g: 9.7985
gradient_error_tolerance: 0.001

# 0.375 for white car, but when debug, use 0.6
gun_pivot_height_above_ground: 0.6
k: 0.0001
learning_rate: 0.002
# 8 * 12 3V3
# base armor height 0.4 m
max_shooting_dis_in_pivot_frame: 12.0
max_shooting_hei_above_ground: 5.0
target_min_hei_above_ground: 0.0

muzzle_x_len: 0.15
muzzle_y_len: 0.0
newton_dx: 0.001
# height error of bullet predicted by newton's method
newton_error_tolerance: 0.011
newton_max_iter: 5
pitch_range:
- -0.7853981633974483
- 0.7853981633974483
yaw_range:
- -3.141592653589793
- 3.141592653589793


camera_init_theta: null
muzzle_init_theta: null
camera_radius: null
muzzle_radius: null
camera_pos_in_gun_pivot_frame: null
muzzle_pos_in_gun_pivot_frame: null
