H:
- - 1
  - 0
  - 0
- - 0
  - 1
  - 0
- - 0
  - 0
  - 1
Q_scale: 0.1
R_scale_dis_diff_denominator: 0.1
armo_distance_variation:
- 0.05
- 0.05
armor_name_to_car_params: {}

history_depth: 5
if_force_correct_after_detect: 1
min_continous_num_to_apply_predict: 3
min_continous_num_to_predict_armor: 3
min_dis_between_continous_detection: 0.1
min_predict_period: 0.1
min_time_between_continous_detection: 0.1
score_accumulation_method_list_for_automatic_matching:
- add
- add
- add
- add
score_criterion_for_automatic_matching: 200
score_weights_list_for_automatic_matching:
- 100
- 10
- 10
- 10
wrongpic_threshold_dis: 0.1